#!/usr/bin/env bash

export PATH="node_modules/.bin:$PATH"

build() {
  rm -r lib/* 2>/dev/null
  babel src -d lib --ignore __tests__ "$@"
  flow-copy-source src lib --ignore '**/__tests__/*'
}

docs() {
  styleguidist server
}

humantest() {
  webpack-dev-server --config humantest/webpack.config.js
}


publish() {
  styleguidist build
  gh-pages -d build.docs
}

case "$1" in
  b | build ) build ;;
  w | watch ) build --watch ;;
  humantest ) humantest ;;
  docs ) docs ;;
  publish ) publish ;;
esac
