#!/usr/bin/env bash

export PATH="node_modules/.bin:$PATH"

build() {
  babel src --out-dir lib --ignore __tests__ "$@"
}

docs() {
  styleguidist server
}

humantest() {
  webpack-dev-server --config humantest/webpack.config.js
}

publish() {
  styleguidist build
  gh-pages -d build.docs
}

case "$1" in
  b | build ) build ;;
  w | watch ) build --watch ;;
  humantest ) humantest ;;
  docs ) docs ;;
  publish ) publish ;;
esac
