// flow-typed signature: 24b9f0d12cdd92c88228a84ba3bca854
// flow-typed version: <<STUB>>/material-components-web_v^0.14.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-components-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-components-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-components-web/dist/material-components-web' {
  declare module.exports: any;
}

declare module 'material-components-web/dist/material-components-web.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-components-web/dist/material-components-web.js' {
  declare module.exports: $Exports<'material-components-web/dist/material-components-web'>;
}
declare module 'material-components-web/dist/material-components-web.min.js' {
  declare module.exports: $Exports<'material-components-web/dist/material-components-web.min'>;
}
declare module 'material-components-web/index' {
  declare module.exports: $Exports<'material-components-web'>;
}
declare module 'material-components-web/index.js' {
  declare module.exports: $Exports<'material-components-web'>;
}
