// flow-typed signature: b262b897b7df4dd826fd2fe3fdb6b370
// flow-typed version: <<STUB>>/@material/animation_v0.2.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/animation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/animation/dist/mdc.animation' {
  declare module.exports: any;
}

declare module '@material/animation/dist/mdc.animation.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/animation/dist/mdc.animation.js' {
  declare module.exports: $Exports<'@material/animation/dist/mdc.animation'>;
}
declare module '@material/animation/dist/mdc.animation.min.js' {
  declare module.exports: $Exports<'@material/animation/dist/mdc.animation.min'>;
}
declare module '@material/animation/index' {
  declare module.exports: $Exports<'@material/animation'>;
}
declare module '@material/animation/index.js' {
  declare module.exports: $Exports<'@material/animation'>;
}
