// flow-typed signature: ff9a41b4fe1432b6cf67a37cc1063244
// flow-typed version: <<STUB>>/@material/checkbox_v0.3.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/checkbox/constants' {
  declare module.exports: any;
}

declare module '@material/checkbox/dist/mdc.checkbox' {
  declare module.exports: any;
}

declare module '@material/checkbox/dist/mdc.checkbox.min' {
  declare module.exports: any;
}

declare module '@material/checkbox/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/checkbox/constants.js' {
  declare module.exports: $Exports<'@material/checkbox/constants'>;
}
declare module '@material/checkbox/dist/mdc.checkbox.js' {
  declare module.exports: $Exports<'@material/checkbox/dist/mdc.checkbox'>;
}
declare module '@material/checkbox/dist/mdc.checkbox.min.js' {
  declare module.exports: $Exports<'@material/checkbox/dist/mdc.checkbox.min'>;
}
declare module '@material/checkbox/foundation.js' {
  declare module.exports: $Exports<'@material/checkbox/foundation'>;
}
declare module '@material/checkbox/index' {
  declare module.exports: $Exports<'@material/checkbox'>;
}
declare module '@material/checkbox/index.js' {
  declare module.exports: $Exports<'@material/checkbox'>;
}
