// flow-typed signature: dd289f57b18e4a1b94678676b365707a
// flow-typed version: <<STUB>>/@material/form-field_v0.2.8/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/form-field'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/form-field' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/form-field/constants' {
  declare module.exports: any;
}

declare module '@material/form-field/dist/mdc.formField' {
  declare module.exports: any;
}

declare module '@material/form-field/dist/mdc.formField.min' {
  declare module.exports: any;
}

declare module '@material/form-field/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/form-field/constants.js' {
  declare module.exports: $Exports<'@material/form-field/constants'>;
}
declare module '@material/form-field/dist/mdc.formField.js' {
  declare module.exports: $Exports<'@material/form-field/dist/mdc.formField'>;
}
declare module '@material/form-field/dist/mdc.formField.min.js' {
  declare module.exports: $Exports<'@material/form-field/dist/mdc.formField.min'>;
}
declare module '@material/form-field/foundation.js' {
  declare module.exports: $Exports<'@material/form-field/foundation'>;
}
declare module '@material/form-field/index' {
  declare module.exports: $Exports<'@material/form-field'>;
}
declare module '@material/form-field/index.js' {
  declare module.exports: $Exports<'@material/form-field'>;
}
