// flow-typed signature: c37503aff0163720d9c39611bcda90a2
// flow-typed version: <<STUB>>/@material/grid-list_v0.2.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/grid-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/grid-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/grid-list/constants' {
  declare module.exports: any;
}

declare module '@material/grid-list/dist/mdc.gridList' {
  declare module.exports: any;
}

declare module '@material/grid-list/dist/mdc.gridList.min' {
  declare module.exports: any;
}

declare module '@material/grid-list/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/grid-list/constants.js' {
  declare module.exports: $Exports<'@material/grid-list/constants'>;
}
declare module '@material/grid-list/dist/mdc.gridList.js' {
  declare module.exports: $Exports<'@material/grid-list/dist/mdc.gridList'>;
}
declare module '@material/grid-list/dist/mdc.gridList.min.js' {
  declare module.exports: $Exports<'@material/grid-list/dist/mdc.gridList.min'>;
}
declare module '@material/grid-list/foundation.js' {
  declare module.exports: $Exports<'@material/grid-list/foundation'>;
}
declare module '@material/grid-list/index' {
  declare module.exports: $Exports<'@material/grid-list'>;
}
declare module '@material/grid-list/index.js' {
  declare module.exports: $Exports<'@material/grid-list'>;
}
