// flow-typed signature: 42ba0f493cdbfad4ba24aa651089a84f
// flow-typed version: <<STUB>>/@material/radio_v0.2.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/radio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/radio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/radio/constants' {
  declare module.exports: any;
}

declare module '@material/radio/dist/mdc.radio' {
  declare module.exports: any;
}

declare module '@material/radio/dist/mdc.radio.min' {
  declare module.exports: any;
}

declare module '@material/radio/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/radio/constants.js' {
  declare module.exports: $Exports<'@material/radio/constants'>;
}
declare module '@material/radio/dist/mdc.radio.js' {
  declare module.exports: $Exports<'@material/radio/dist/mdc.radio'>;
}
declare module '@material/radio/dist/mdc.radio.min.js' {
  declare module.exports: $Exports<'@material/radio/dist/mdc.radio.min'>;
}
declare module '@material/radio/foundation.js' {
  declare module.exports: $Exports<'@material/radio/foundation'>;
}
declare module '@material/radio/index' {
  declare module.exports: $Exports<'@material/radio'>;
}
declare module '@material/radio/index.js' {
  declare module.exports: $Exports<'@material/radio'>;
}
