// flow-typed signature: 9e86d2506f2332a0ac0cb877776b7ff2
// flow-typed version: <<STUB>>/@material/ripple_v0.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/ripple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/ripple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/ripple/constants' {
  declare module.exports: any;
}

declare module '@material/ripple/dist/mdc.ripple' {
  declare module.exports: any;
}

declare module '@material/ripple/dist/mdc.ripple.min' {
  declare module.exports: any;
}

declare module '@material/ripple/foundation' {
  declare module.exports: any;
}

declare module '@material/ripple/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/ripple/constants.js' {
  declare module.exports: $Exports<'@material/ripple/constants'>;
}
declare module '@material/ripple/dist/mdc.ripple.js' {
  declare module.exports: $Exports<'@material/ripple/dist/mdc.ripple'>;
}
declare module '@material/ripple/dist/mdc.ripple.min.js' {
  declare module.exports: $Exports<'@material/ripple/dist/mdc.ripple.min'>;
}
declare module '@material/ripple/foundation.js' {
  declare module.exports: $Exports<'@material/ripple/foundation'>;
}
declare module '@material/ripple/index' {
  declare module.exports: $Exports<'@material/ripple'>;
}
declare module '@material/ripple/index.js' {
  declare module.exports: $Exports<'@material/ripple'>;
}
declare module '@material/ripple/util.js' {
  declare module.exports: $Exports<'@material/ripple/util'>;
}
