// flow-typed signature: 6f3c43e533e0f797c7371ebf7bf57785
// flow-typed version: <<STUB>>/@material/select_v0.3.9/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/select/constants' {
  declare module.exports: any;
}

declare module '@material/select/dist/mdc.select' {
  declare module.exports: any;
}

declare module '@material/select/dist/mdc.select.min' {
  declare module.exports: any;
}

declare module '@material/select/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/select/constants.js' {
  declare module.exports: $Exports<'@material/select/constants'>;
}
declare module '@material/select/dist/mdc.select.js' {
  declare module.exports: $Exports<'@material/select/dist/mdc.select'>;
}
declare module '@material/select/dist/mdc.select.min.js' {
  declare module.exports: $Exports<'@material/select/dist/mdc.select.min'>;
}
declare module '@material/select/foundation.js' {
  declare module.exports: $Exports<'@material/select/foundation'>;
}
declare module '@material/select/index' {
  declare module.exports: $Exports<'@material/select'>;
}
declare module '@material/select/index.js' {
  declare module.exports: $Exports<'@material/select'>;
}
