// flow-typed signature: 18e1d805abeabd1f0ff077734ff669fa
// flow-typed version: <<STUB>>/@material/tabs_v0.2.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/tabs/dist/mdc.tabs' {
  declare module.exports: any;
}

declare module '@material/tabs/dist/mdc.tabs.min' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar-scroller/constants' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar-scroller/foundation' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar-scroller/index' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar/constants' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar/foundation' {
  declare module.exports: any;
}

declare module '@material/tabs/tab-bar/index' {
  declare module.exports: any;
}

declare module '@material/tabs/tab/constants' {
  declare module.exports: any;
}

declare module '@material/tabs/tab/foundation' {
  declare module.exports: any;
}

declare module '@material/tabs/tab/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/tabs/dist/mdc.tabs.js' {
  declare module.exports: $Exports<'@material/tabs/dist/mdc.tabs'>;
}
declare module '@material/tabs/dist/mdc.tabs.min.js' {
  declare module.exports: $Exports<'@material/tabs/dist/mdc.tabs.min'>;
}
declare module '@material/tabs/index' {
  declare module.exports: $Exports<'@material/tabs'>;
}
declare module '@material/tabs/index.js' {
  declare module.exports: $Exports<'@material/tabs'>;
}
declare module '@material/tabs/tab-bar-scroller/constants.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar-scroller/constants'>;
}
declare module '@material/tabs/tab-bar-scroller/foundation.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar-scroller/foundation'>;
}
declare module '@material/tabs/tab-bar-scroller/index.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar-scroller/index'>;
}
declare module '@material/tabs/tab-bar/constants.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar/constants'>;
}
declare module '@material/tabs/tab-bar/foundation.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar/foundation'>;
}
declare module '@material/tabs/tab-bar/index.js' {
  declare module.exports: $Exports<'@material/tabs/tab-bar/index'>;
}
declare module '@material/tabs/tab/constants.js' {
  declare module.exports: $Exports<'@material/tabs/tab/constants'>;
}
declare module '@material/tabs/tab/foundation.js' {
  declare module.exports: $Exports<'@material/tabs/tab/foundation'>;
}
declare module '@material/tabs/tab/index.js' {
  declare module.exports: $Exports<'@material/tabs/tab/index'>;
}
