// flow-typed signature: c5a45880494e6d031633fb448ae0ca42
// flow-typed version: <<STUB>>/@material/textfield_v0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/textfield'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/textfield' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/textfield/constants' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield' {
  declare module.exports: any;
}

declare module '@material/textfield/dist/mdc.textfield.min' {
  declare module.exports: any;
}

declare module '@material/textfield/foundation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/textfield/constants.js' {
  declare module.exports: $Exports<'@material/textfield/constants'>;
}
declare module '@material/textfield/dist/mdc.textfield.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield'>;
}
declare module '@material/textfield/dist/mdc.textfield.min.js' {
  declare module.exports: $Exports<'@material/textfield/dist/mdc.textfield.min'>;
}
declare module '@material/textfield/foundation.js' {
  declare module.exports: $Exports<'@material/textfield/foundation'>;
}
declare module '@material/textfield/index' {
  declare module.exports: $Exports<'@material/textfield'>;
}
declare module '@material/textfield/index.js' {
  declare module.exports: $Exports<'@material/textfield'>;
}
